server:
  port: 9000
spring:
  application:
    name: inv-market-svc
  profiles:
    active: "local"
    include: "message"
  security:
    client:
      retryable:
        maxAttempts: 3
        period: 3000
      options:
        readTimeoutMill: 30000
        writeTimeoutMill: 15000
        responseTimeoutMill: 30000
    duration:
      minOfSeconds: 3
      maxOfSecons: 7
      timeOutOfSecond: 30

    registration:
      vcb-broker:
        clientId: "CKRJ0KJA5MM8JUZWCWKL"
        clientSecret: "JcPk4Yoecn9BVuzpU91KeZgPS9HON6eZuOwE4apo"
        url: "https://broker-api.sandbox.alpaca.markets"
        authenticationType: "basic"
      vcb-market:
        clientId: "CKRJ0KJA5MM8JUZWCWKL"
        clientSecret: "JcPk4Yoecn9BVuzpU91KeZgPS9HON6eZuOwE4apo"
        url: "https://data.sandbox.alpaca.markets"
        authenticationType: "basic"
