cloud:
  aws:
    region: eu-central-1
    sqs:
      rootUrl: http://localhost:4566/000000000000
      common:
        waitTimeOut: 20
        maxNumberOfMessages: 10
        maxInflightMessagesPerQueue: 10
        maxMessagesPerPoll: 10
        pollTimeout: 10
        permitAcquireTimeout: 30
        corePoolSize: 30
        maxPoolSize: 30
        keepAliveTimeInSeconds: 60
        threadNamePrefix: "sqs_consumer_common_thread_"
      inv-market-data-collection-queue: inv-market-data-collection-queue
      isDefaultCredential: true