server:
  port: 9000
spring:
  application:
    name: inv-market-svc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_investment
    username: root
    password: C0C0nutP1e
  
  profiles:
    active: "local"
    include: "message"
  security:
    client:
      retryable:
        maxAttempts: 3
        period: 3000
      options:
        readTimeoutMill: 30000
        writeTimeoutMill: 15000
        responseTimeoutMill: 30000
      duration:
        minOfSeconds: 3
        maxOfSecons: 7
        timeOutOfSecond: 30
      registration:
        vcb-broker:
          clientId: "CK7SH6JUA9NRJE7BJMKF"
          clientSecret: "CmXXAmj5zthc6nYdPLua4t8JO2kXv3pW3gQ0y43I"
          url: "https://broker-api.sandbox.alpaca.markets"
          authenticationType: "basic"
        vcb-market:
          clientId: "CK7SH6JUA9NRJE7BJMKF"
          clientSecret: "CmXXAmj5zthc6nYdPLua4t8JO2kXv3pW3gQ0y43I"
          url: "https://data.sandbox.alpaca.markets"
          authenticationType: "basic"
